const APP_VERSION='2026-06-22.6';
const KEY='waterTracker_v1';
const quick=[8,12,16,20,30];
const defaults={goal:120,weekdayGoal:120,weekendGoal:100,goalMode:'daily',theme:'system',cups:[{id:'owala',name:'Owala',oz:24},{id:'mug',name:'Mug',oz:12},{id:'stanley',name:'Stanley',oz:40}],days:{},backups:{}};
let state=load(),editingCupId=null,timelineOpen=false;
function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));let x=s?{...defaults,...s,cups:s.cups?.length?s.cups:defaults.cups,days:s.days||{},backups:s.backups||{}}:structuredClone(defaults);x.cups=x.cups.map(c=>({...c,id:c.id||uid()}));return x}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dayKey(d=new Date()){const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)}
function dateFromKey(k){const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d)}
function goalFor(k=dayKey()){if(state.goalMode==='weekdayWeekend'){const d=dateFromKey(k).getDay();return d===0||d===6?Number(state.weekendGoal||state.goal):Number(state.weekdayGoal||state.goal)}return Number(state.goal||120)}
function today(){const k=dayKey();if(!state.days[k])state.days[k]={drinks:[]};return state.days[k]}
function drinks(k=dayKey()){return state.days[k]?.drinks||[]}
function total(k=dayKey()){return drinks(k).reduce((s,d)=>s+Number(d.oz||0),0)}
function localBackup(){const k=dayKey();state.backups=state.backups||{};state.backups[k]=JSON.parse(JSON.stringify(today()));const keys=Object.keys(state.backups).sort();while(keys.length>30){delete state.backups[keys.shift()]}}
function add(oz,label='Quick add'){oz=Number(oz);if(!oz||oz<1)return;const before=total(),g=goalFor();today().drinks.push({id:uid(),oz,label,at:new Date().toISOString()});localBackup();save();render();slosh();navigator.vibrate?.(20);const after=total();if(before<g&&after>=g){toast(`Goal hit: ${after} oz`);celebrate()}else toast(`Added ${oz} oz`)}
function undo(){const d=today().drinks.pop();if(!d)return;localBackup();save();render();toast(`Undid ${d.oz} oz`)}
function openAmount(){document.getElementById('amountInput').value='';document.getElementById('amountDialog').showModal();setTimeout(()=>document.getElementById('amountInput').focus(),60)}
function saveAmount(e){const oz=Number(document.getElementById('amountInput').value);if(!oz||oz<1){e.preventDefault();alert('Enter a valid ounce amount.');return}add(oz,'Custom amount')}
function openCup(id=null){editingCupId=id;const c=state.cups.find(x=>x.id===id);document.getElementById('cupTitle').textContent=c?'Edit Cup':'Add Cup';document.getElementById('cupName').value=c?.name||'';document.getElementById('cupOz').value=c?.oz||'';document.getElementById('deleteCup').style.display=c?'block':'none';document.getElementById('cupDialog').showModal();setTimeout(()=>document.getElementById('cupName').focus(),60)}
function saveCup(e){const name=document.getElementById('cupName').value.trim(),oz=Number(document.getElementById('cupOz').value);if(!name||!oz||oz<1){e.preventDefault();alert('Enter a cup name and valid ounce amount.');return}if(editingCupId){const c=state.cups.find(x=>x.id===editingCupId);if(c){c.name=name;c.oz=oz;toast('Cup updated')}}else{state.cups.push({id:uid(),name,oz});toast('Cup added')}save();setTimeout(render,0)}
function deleteCup(e){e.preventDefault();if(!editingCupId)return;const c=state.cups.find(x=>x.id===editingCupId);if(c&&confirm(`Delete ${c.name}?`)){state.cups=state.cups.filter(x=>x.id!==editingCupId);save();document.getElementById('cupDialog').close();render();toast('Cup deleted')}}
function openSettings(){document.getElementById('goalInput').value=state.goal;document.getElementById('weekdayGoalInput').value=state.weekdayGoal||state.goal;document.getElementById('weekendGoalInput').value=state.weekendGoal||state.goal;document.getElementById('goalModeInput').value=state.goalMode||'daily';document.getElementById('themeInput').value=state.theme||'system';document.getElementById('settingsDialog').showModal()}
function saveSettings(e){const goal=Number(document.getElementById('goalInput').value),wg=Number(document.getElementById('weekdayGoalInput').value),eg=Number(document.getElementById('weekendGoalInput').value);if(!goal||goal<1||!wg||wg<1||!eg||eg<1){e.preventDefault();alert('Enter valid goals.');return}state.goal=goal;state.weekdayGoal=wg;state.weekendGoal=eg;state.goalMode=document.getElementById('goalModeInput').value;state.theme=document.getElementById('themeInput').value;save();applyTheme();setTimeout(render,0);toast('Settings saved')}
function editCups(e){e.preventDefault();document.getElementById('settingsDialog').close();toast('Tap any cup to edit for 5 seconds');window.editingCups=true;setTimeout(()=>{window.editingCups=false;render()},5000)}
function applyTheme(){const pref=matchMedia('(prefers-color-scheme:dark)').matches;document.documentElement.dataset.theme=(state.theme||'system')==='system'?(pref?'dark':'light'):state.theme}
function streaks(){let cur=0,best=0,run=0;for(let i=365;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=dayKey(d),met=total(k)>=goalFor(k);run=met?run+1:0;best=Math.max(best,run)}for(let i=0;i<365;i++){const d=new Date();d.setDate(d.getDate()-i);const k=dayKey(d);if(total(k)>=goalFor(k))cur++;else break}return{cur,best}}
function render(){today();const k=dayKey(),g=goalFor(k),t=total(),pctRaw=t/g*100,pct=Math.min(100,Math.round(pctRaw));document.getElementById('total').textContent=t;document.getElementById('goal').textContent=g;document.getElementById('status').textContent=`${Math.round(pctRaw)}% complete`;document.getElementById('water').style.height=pct+'%';const st=streaks();document.getElementById('streak').textContent=st.cur;document.getElementById('bestStreak').textContent=st.best;document.getElementById('goalMode').textContent=state.goalMode==='weekdayWeekend'?'Split':'Daily';renderQuick();renderCups();renderUndo();renderHistory();renderTimeline()}
function renderQuick(){const q=document.getElementById('quick');q.innerHTML='';quick.forEach(oz=>{const b=document.createElement('button');b.className='add';b.textContent='+'+oz;b.onclick=()=>add(oz);q.appendChild(b)});const c=document.createElement('button');c.className='add custom';c.textContent='+ Custom';c.onclick=openAmount;q.appendChild(c)}
function renderCups(){const box=document.getElementById('cups');box.innerHTML='';state.cups.forEach(c=>{const b=document.createElement('button');b.className='cup';b.innerHTML=`+${esc(c.oz)}<span>${esc(c.name)}</span>`;b.onclick=()=>window.editingCups?openCup(c.id):add(c.oz,c.name);b.oncontextmenu=e=>{e.preventDefault();openCup(c.id)};box.appendChild(b)})}
function renderUndo(){const last=today().drinks.at(-1),u=document.getElementById('undo');u.disabled=!last;u.textContent=last?`↶ Undo +${last.oz} oz`:'↶ Undo last drink'}
function renderHistory(){const h=document.getElementById('history');h.innerHTML='';let sum=0;for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const k=dayKey(d),oz=total(k),g=goalFor(k),p=Math.round(oz/g*100);sum+=oz;const el=document.createElement('button');el.className='day'+(oz>=g?' met':p>=80?' close':'')+(k===dayKey()?' today':'');el.innerHTML=`<div><div class="dow">${d.toLocaleDateString(undefined,{weekday:'short'})}</div><div class="oz">${oz}</div><div class="pct">${p}%</div></div>`;el.onclick=()=>openDay(k);h.appendChild(el)}document.getElementById('avg').textContent=`Avg ${Math.round(sum/7)} oz`}
function openDay(k){const d=dateFromKey(k),oz=total(k),g=goalFor(k),list=drinks(k);document.getElementById('dayTitle').textContent=`${d.toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'})} · ${oz}/${g} oz`;const box=document.getElementById('dayDetails');box.innerHTML=list.length?'':'<div class="drink">No drinks logged</div>';[...list].reverse().forEach(x=>{const time=new Date(x.at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});const row=document.createElement('div');row.className='drink';row.innerHTML=`<span>${time} · ${esc(x.label||'Drink')}</span><strong>+${esc(x.oz)} oz</strong>`;box.appendChild(row)});document.getElementById('dayDialog').showModal()}
function renderTimeline(){const box=document.getElementById('timeline'),btn=document.getElementById('toggleTimeline');box.className='timeline'+(timelineOpen?' show':'');btn.textContent=timelineOpen?'Hide':'Show';box.innerHTML='';const ds=[...drinks()].reverse();if(!ds.length){box.innerHTML='<div class="drink">No drinks logged yet</div>';return}ds.forEach(d=>{const time=new Date(d.at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});const row=document.createElement('div');row.className='drink';row.innerHTML=`<span>${time} · ${esc(d.label||'Drink')}</span><strong>+${esc(d.oz)} oz</strong>`;box.appendChild(row)})}
function slosh(){const w=document.getElementById('water');w.classList.remove('slosh');void w.offsetWidth;w.classList.add('slosh')}
function celebrate(){document.getElementById('hero').classList.remove('celebrate');void document.getElementById('hero').offsetWidth;document.getElementById('hero').classList.add('celebrate');navigator.vibrate?.([25,40,25]);const wrap=document.getElementById('confetti');wrap.innerHTML='';for(let i=0;i<24;i++){const d=document.createElement('div');d.className='dot';d.style.left=Math.random()*100+'vw';d.style.background=['#35aef4','#19a974','#ffd166','#ef476f'][i%4];d.style.animationDelay=Math.random()*0.25+'s';wrap.appendChild(d)}setTimeout(()=>wrap.innerHTML='',1200)}
function esc(v){return String(v).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
let timer;function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('show'),1400)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='water-tracker-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=()=>{const file=input.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data.days)throw new Error('bad');state={...defaults,...data};save();render();toast('Data imported')}catch{alert('That backup file was not valid.')}};reader.readAsText(file)};input.click()}
async function checkForUpdate(){try{const res=await fetch('app.js?check='+Date.now(),{cache:'no-store'}),txt=await res.text(),m=txt.match(/APP_VERSION='([^']+)'/);if(m&&m[1]!==APP_VERSION)document.getElementById('updateBanner').classList.add('show')}catch{}}
function wire(){document.getElementById('addCup').onclick=()=>openCup();document.getElementById('settings').onclick=openSettings;document.getElementById('undo').onclick=undo;document.getElementById('saveAmount').onclick=saveAmount;document.getElementById('saveCup').onclick=saveCup;document.getElementById('deleteCup').onclick=deleteCup;document.getElementById('saveSettings').onclick=saveSettings;document.getElementById('editCups').onclick=editCups;document.getElementById('toggleTimeline').onclick=()=>{timelineOpen=!timelineOpen;renderTimeline()};document.getElementById('updateNow').onclick=()=>location.reload();document.getElementById('exportData').onclick=exportData;document.getElementById('importData').onclick=importData;matchMedia('(prefers-color-scheme:dark)').addEventListener('change',applyTheme)}
wire();applyTheme();render();setTimeout(checkForUpdate,800);
