(function(){
const S=WT_V1_STORAGE,H=WT_V1_HYDRATION,E=WT_V1_ENGAGEMENT,P=WT_V1_PLANTS,D=WT_V1_DATE;
const api=()=>H.createApi(S.load(),()=>{});
const DROP_COUNTS={dry:0,damp:3,moist:6,watered:10};let busy=false,checking=false;
function lifetimeGoalDays(state){return WT_V1_STATS.calculate(H.createApi(state,()=>{})).goalDays;}
function ensureCompletion(){if(checking)return false;checking=true;try{const state=S.load(),pp=state.plantProgress||{},life=P.progress(state,lifetimeGoalDays(state));if(!life.complete||pp.completionPending)return false;const completed=Array.isArray(pp.completedPlants)?pp.completedPlants:[];if(!completed.some(x=>(typeof x==='string'?x:x?.plantId)===life.plantId))completed.push({plantId:life.plantId,name:life.plant.name,completedAt:new Date().toISOString(),goalDays:life.goalDays});const pool=P.mysteryPool(completed.map(x=>typeof x==='string'?x:x?.plantId).filter(Boolean)),next=pool.length?pool[Math.floor(Math.random()*pool.length)]:null;pp.completedPlants=completed;pp.completionPending={plantId:life.plantId,plantName:life.plant.name,completedAt:new Date().toISOString(),goalDays:life.goalDays};pp.nextSeed=next?{plantId:next.id,awardedAt:new Date().toISOString()}:null;state.plantProgress=pp;S.save(state);return true;}finally{checking=false;}}
function plantMysterySeed(){const state=S.load(),pp=state.plantProgress||{},seed=pp.nextSeed;if(!pp.completionPending||!seed?.plantId)return false;const next=P.definition(seed.plantId);if(!next||next.enabled===false)return false;pp.currentPlantId=next.id;pp.startedAtGoalDays=lifetimeGoalDays(state);pp.startedAtDate=D.dayKey();pp.completionPending=null;pp.nextSeed=null;state.plantProgress=pp;S.save(state);return next;}
function dropletMarkup(m){const count=DROP_COUNTS[m]??0;let html='';for(let i=0;i<count;i++)html+='<i class="plantDrop plantDropSmall drop-'+(i+1)+'"></i>';for(let i=0;i<count;i++)html+='<i class="plantDrop plantDropLarge drop-'+(i+1)+'"></i>';return html;}
function buildFlowerPulses(scene,flowerAnimation,ratio){const layer=scene.querySelector('.flowerPulseLayer');if(!layer||!flowerAnimation||!Array.isArray(flowerAnimation.layers)||!flowerAnimation.layers.length)return;const hydration=Math.max(0,Math.min(1,Number(ratio)||0)),period=hydration>0?1/hydration:0,layers=flowerAnimation.layers;layers.forEach((item,i)=>{const delay=period>0?(-period*(i/(Math.max(1,layers.length)*2))).toFixed(3)+'s':'0s';if(item.box){const b=item.box,wrap=document.createElement('span'),img=document.createElement('img');wrap.className='flowerPulseCrop';wrap.setAttribute('aria-hidden','true');wrap.style.left=b.x+'%';wrap.style.top=b.y+'%';wrap.style.width=b.w+'%';wrap.style.height=b.h+'%';wrap.style.transformOrigin=item.cx+'% '+item.cy+'%';wrap.style.setProperty('--flower-scale',String(item.scale||1.08));if(period>0){wrap.style.setProperty('--flower-period',period.toFixed(3)+'s');wrap.style.animationDelay=delay;}else wrap.classList.add('flowerStill');img.className='flowerPulseSource';img.src=item.asset;img.alt='';img.style.left=(-b.x/b.w*100)+'%';img.style.top=(-b.y/b.h*100)+'%';img.style.width=(10000/b.w)+'%';img.style.height=(10000/b.h)+'%';wrap.appendChild(img);layer.appendChild(wrap);return;}const img=document.createElement('img');img.className='flowerPulse flowerAssetPulse';img.src=item.asset;img.alt='';img.setAttribute('aria-hidden','true');img.style.transformOrigin=item.cx+'% '+item.cy+'%';img.style.setProperty('--flower-scale',String(item.scale||1.018));if(period>0){img.style.setProperty('--flower-period',period.toFixed(3)+'s');img.style.animationDelay=delay;}else img.classList.add('flowerStill');layer.appendChild(img);});}
function handoffMarkup(p){if(!p.completionPending)return'';if(p.nextSeed)return'<div class="plantCompletion"><strong>🌟 '+p.plantName+' complete!</strong><span>You earned a Mystery Seed.</span><button type="button" class="plantSeedButton">🌱 Plant Mystery Seed</button></div>';return'<div class="plantCompletion"><strong>🌟 '+p.plantName+' complete!</strong><span>Your garden is caught up — more Mystery Seeds are coming.</span></div>';}
async function render(){if(busy)return;busy=true;try{ensureCompletion();const p=E.plant(api()),box=document.getElementById('plantBox'),name=document.getElementById('plantName');if(!box)return;const def=P.definition(p.plantId),stages=def.stages,next=stages[p.stage+1],min=stages[p.stage]?.minGoalDays||0,max=next?.minGoalDays||Math.max(min+1,p.durationGoalDays),progress=next?Math.max(0,Math.min(100,((p.goalDays-min)/(max-min))*100)):100,moisture=String(p.moisture||'dry').replace(/[^a-z0-9_-]/gi,'');if(name)name.textContent=p.name;box.className='plant spritePlant staticConceptPlant moisture-'+moisture;box.dataset.moisture=moisture;box.dataset.stage=String(p.stage);box.dataset.plantId=p.plantId;box.innerHTML='<div class="spritePlantScene staticConceptScene moisture-'+moisture+'" data-moisture="'+moisture+'"><img class="plantConceptArt" src="'+p.asset+'" alt="'+p.name+' plant"><div class="flowerPulseLayer" aria-hidden="true"></div><div class="plantEffectLayer" aria-hidden="true">'+dropletMarkup(moisture)+'</div></div><div><p class="plantCondition">'+p.moistureText+'</p><p class="plantMeta">Today: '+p.today+' / '+p.goal+' oz</p><p class="plantMeta">'+p.goalDays+' plant goal days'+(next?' · next: '+next.name+' at '+next.minGoalDays:' · fully grown')+'</p><div class="plantGrowthTrack"><span style="width:'+progress+'%"></span></div>'+handoffMarkup(p)+'</div>';buildFlowerPulses(box.querySelector('.spritePlantScene'),p.flowerAnimation,p.ratio);const seedButton=box.querySelector('.plantSeedButton');if(seedButton)seedButton.onclick=()=>{seedButton.disabled=true;const nextPlant=plantMysterySeed();if(nextPlant){render();}else seedButton.disabled=false;};}finally{busy=false;}}
['storage','wt-data-changed','wt-plant-render'].forEach(t=>window.addEventListener(t,render));render();setTimeout(render,300);
})();
(function(){const s=document.createElement('script');s.src='v1/js/garden.js';s.defer=true;document.head.appendChild(s);})();